--- #YAML:1.0
name:                Wiki-Toolkit-Plugin-Categoriser
version:             0.06
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Test::More:                    0
    Wiki::Toolkit:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
