# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Wiki-Toolkit-Plugin-Categoriser
version:      0.05
version_from: lib/Wiki/Toolkit/Plugin/Categoriser.pm
installdirs:  site
requires:
    Carp:                          0
    Test::More:                    0
    Wiki::Toolkit:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
